/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class vehiculomenu extends javax.swing.JFrame {

    /**
     * Creates new form vehiculomenu
     */
    public vehiculomenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpOpciones = new javax.swing.ButtonGroup();
        rbtnNuevo = new javax.swing.JRadioButton();
        rbtnActualizar = new javax.swing.JRadioButton();
        rbtnListar = new javax.swing.JRadioButton();
        RbtnEliminar = new javax.swing.JRadioButton();
        btnContinuar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGrpOpciones.add(rbtnNuevo);
        rbtnNuevo.setForeground(new java.awt.Color(255, 102, 102));
        rbtnNuevo.setText("Nuevo vehiculo");

        btnGrpOpciones.add(rbtnActualizar);
        rbtnActualizar.setForeground(new java.awt.Color(255, 102, 102));
        rbtnActualizar.setText("Actualizar vehiculo");

        btnGrpOpciones.add(rbtnListar);
        rbtnListar.setForeground(new java.awt.Color(255, 153, 153));
        rbtnListar.setText("Reportar Vehiculo");

        btnGrpOpciones.add(RbtnEliminar);
        RbtnEliminar.setForeground(new java.awt.Color(255, 153, 153));
        RbtnEliminar.setText("Eliminar Vehiculo");
        RbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnEliminarActionPerformed(evt);
            }
        });

        btnContinuar.setText("Continuar");
        btnGrpOpciones.add(btnContinuar);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnGrpOpciones.add(btnCancelar);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnGrpOpciones.add(btnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnNuevo)
                    .addComponent(rbtnActualizar)
                    .addComponent(rbtnListar)
                    .addComponent(RbtnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnContinuar)
                .addGap(50, 50, 50)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(rbtnNuevo)
                .addGap(18, 18, 18)
                .addComponent(rbtnActualizar)
                .addGap(18, 18, 18)
                .addComponent(rbtnListar)
                .addGap(18, 18, 18)
                .addComponent(RbtnEliminar)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnEliminarActionPerformed
        
    }//GEN-LAST:event_RbtnEliminarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        
        if(rbtnNuevo.isSelected())
        {   
            vehiculomenu.this.dispose();
            vehiculonuevo  nuevo= new vehiculonuevo();
            nuevo.setVisible(true);
            nuevo.setLocationRelativeTo(null);
        }
        else
        {
        if(rbtnActualizar.isSelected())
        {   
            vehiculomenu.this.dispose();
            vehiculonuevo  nuevo= new vehiculonuevo();
            nuevo.setVisible(true);
            nuevo.setLocationRelativeTo(null);
        }
        
        if(rbtnListar.isSelected())
        {   
            vehiculomenu.this.dispose();
            vehiculolistar  listar= new vehiculolistar();
            listar.setVisible(true);
            listar.setLocationRelativeTo(null);
            
        }

        }
        
       
        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    
            
    }//GEN-LAST:event_btnCancelarActionPerformed


    
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehiculomenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtnEliminar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup btnGrpOpciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton rbtnActualizar;
    private javax.swing.JRadioButton rbtnListar;
    private javax.swing.JRadioButton rbtnNuevo;
    // End of variables declaration//GEN-END:variables
}
